typo found in function name (satus -> status)
cagatayuresin/odoo-xmlrpc-wrapper pull request #1
Opened 2023-05-22 12:28 UTC by honeypool

first time contributing on github

2023-05-24 08:07 UTC, ecralx requested changes

2023-05-24 08:07 UTC, ecralx commented on src/odoo_xmlrpc_wrapper/odoo_xmlrpc_wrapper.py
> +    def status(self) -> str:
Hello ! I think you'll also need to add the `@property` to the method (or call `self.status()`) ! Thanks

2023-12-03 15:40 UTC, Warrio111 commented
Please merge

2024-06-26 01:33 UTC, ddean6232 commented
Please merge

2026-04-22 05:34 UTC, merged